// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VSMS.Infrastructure.Data.EfCoreQuery;

#nullable disable

namespace VSMS.Infrastructure.Data.EfCoreQuery.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326053151_TemplateType")]
    partial class TemplateType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VSMS.Infrastructure.Data.EfCoreQuery.Entities.AdminEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GrainId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("VSMS.Infrastructure.Data.EfCoreQuery.Entities.ApplicationReadModel", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid");

                    b.Property<string>("OpportunityTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ShiftEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.Property<string>("VolunteerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ApplicationId");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("VolunteerId");

                    b.HasIndex("OpportunityId", "AppliedAt")
                        .HasDatabaseName("IX_ApplicationReadModels_OpportunityId_AppliedAt");

                    b.HasIndex("VolunteerId", "AppliedAt")
                        .HasDatabaseName("IX_ApplicationReadModels_VolunteerId_AppliedAt");

                    b.ToTable("ApplicationReadModels");
                });

            modelBuilder.Entity("VSMS.Infrastructure.Data.EfCoreQuery.Entities.AttendanceReadModel", b =>
                {
                    b.Property<Guid>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid");

                    b.Property<string>("OpportunityTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ShiftStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double>("TotalHours")
                        .HasColumnType("double precision");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.Property<string>("VolunteerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("AttendanceId");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("OpportunityId", "ShiftStartTime")
                        .HasDatabaseName("IX_AttendanceReadModels_OpportunityId_ShiftStartTime");

                    b.HasIndex("VolunteerId", "CheckInTime")
                        .HasDatabaseName("IX_AttendanceReadModels_VolunteerId_CheckInTime");

                    b.ToTable("AttendanceReadModels");
                });

            modelBuilder.Entity("VSMS.Infrastructure.Data.EfCoreQuery.Entities.CertificateTemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("BackgroundFileKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BodyTemplate")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoFileKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SignatoryName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SignatoryTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TitleText")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("CertificateTemplates");
                });

            modelBuilder.Entity("VSMS.Infrastructure.Data.EfCoreQuery.Entities.CoordinatorEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GrainId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Coordinators");
                });

            modelBuilder.Entity("VSMS.Infrastructure.Data.EfCoreQuery.Entities.DisputeReadModel", b =>
                {
                    b.Property<Guid>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EvidenceUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OpportunityTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("RaisedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.Property<string>("VolunteerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("AttendanceId");

                    b.HasIndex("RaisedAt")
                        .HasDatabaseName("IX_DisputeReadModels_RaisedAt");

                    b.HasIndex("VolunteerId");

                    b.ToTable("DisputeReadModels");
                });

            modelBuilder.Entity("VSMS.Infrastructure.Data.EfCoreQuery.Entities.EventTaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedToEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("AssignedToGrainId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedToName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("CreatedByGrainId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("EventTasks");
                });

            modelBuilder.Entity("VSMS.Infrastructure.Data.EfCoreQuery.Entities.EventTemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalPolicy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RadiusMeters")
                        .HasColumnType("integer");

                    b.Property<string>("RequiredSkillIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("EventTemplates");
                });

            modelBuilder.Entity("VSMS.Infrastructure.Data.EfCoreQuery.Entities.NotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderName")
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VolunteerGrainId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VolunteerGrainId", "SentAt")
                        .HasDatabaseName("IX_Notifications_VolunteerGrainId_SentAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("VSMS.Infrastructure.Data.EfCoreQuery.Entities.OpportunityReadModel", b =>
                {
                    b.Property<Guid>("OpportunityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AvailableSpots")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequiredSkillIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalSpots")
                        .HasColumnType("integer");

                    b.HasKey("OpportunityId");

                    b.HasIndex("Category");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "PublishDate")
                        .HasDatabaseName("IX_OpportunityReadModels_Status_PublishDate");

                    b.ToTable("OpportunityReadModels");
                });

            modelBuilder.Entity("VSMS.Infrastructure.Data.EfCoreQuery.Entities.OrganizationReadModel", b =>
                {
                    b.Property<Guid>("OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("LatestAnnouncementAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LatestAnnouncementText")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("OrgId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_OrganizationReadModels_Status_CreatedAt");

                    b.ToTable("OrganizationReadModels");
                });

            modelBuilder.Entity("VSMS.Infrastructure.Data.EfCoreQuery.Entities.SkillEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("VSMS.Infrastructure.Data.EfCoreQuery.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsBanned")
                        .HasDatabaseName("IX_Users_IsBanned");

                    b.HasIndex("Role", "CreatedAt")
                        .HasDatabaseName("IX_Users_Role_CreatedAt");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VSMS.Infrastructure.Data.EfCoreQuery.Entities.VolunteerEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GrainId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("VSMS.Infrastructure.Data.EfCoreQuery.Entities.VolunteerFollowEntity", b =>
                {
                    b.Property<Guid>("VolunteerGrainId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FollowedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VolunteerGrainId", "OrgId");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("IX_VolunteerFollows_OrgId");

                    b.ToTable("VolunteerFollows");
                });

            modelBuilder.Entity("VSMS.Infrastructure.Data.EfCoreQuery.Entities.AdminEntity", b =>
                {
                    b.HasOne("VSMS.Infrastructure.Data.EfCoreQuery.Entities.UserEntity", "User")
                        .WithOne("AdminProfile")
                        .HasForeignKey("VSMS.Infrastructure.Data.EfCoreQuery.Entities.AdminEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VSMS.Infrastructure.Data.EfCoreQuery.Entities.CoordinatorEntity", b =>
                {
                    b.HasOne("VSMS.Infrastructure.Data.EfCoreQuery.Entities.UserEntity", "User")
                        .WithOne("CoordinatorProfile")
                        .HasForeignKey("VSMS.Infrastructure.Data.EfCoreQuery.Entities.CoordinatorEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VSMS.Infrastructure.Data.EfCoreQuery.Entities.VolunteerEntity", b =>
                {
                    b.HasOne("VSMS.Infrastructure.Data.EfCoreQuery.Entities.UserEntity", "User")
                        .WithOne("VolunteerProfile")
                        .HasForeignKey("VSMS.Infrastructure.Data.EfCoreQuery.Entities.VolunteerEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VSMS.Infrastructure.Data.EfCoreQuery.Entities.UserEntity", b =>
                {
                    b.Navigation("AdminProfile");

                    b.Navigation("CoordinatorProfile");

                    b.Navigation("VolunteerProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
