server {
    listen 8081;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location /download/ {
        types { application/vnd.android.package-archive apk; }
        default_type application/octet-stream;
        add_header Content-Disposition "attachment";
    }
}